.test-template: &test
  cache:
    paths:
      - vendor/ruby
  before_script:
    - gem install bundler --no-document
    - bundle config set --local path 'vendor/bundle'
    - bundle config set --local without 'development'
    - bundle install -j $(nproc)
    - ruby -v                                   # Print out ruby version for debugging
  script:
    - bundle exec rake compile
    - bundle exec rake test

default:
  image: "ruby:${RUBY_VERSION}"

rspec:
  parallel:
    matrix:
      - RUBY_VERSION: [ "2.5", "2.6", "2.7", "3.0" ]
  <<: *test

truffleruby:
  image: "flavorjones/truffleruby:buster"
  allow_failure: true
  <<: *test
